window.MTM_RESOURCE_COPY = {
  en: {},
  nl: {
    skip: "Ga naar het materiaal",
    brandSub: "Onderzoek naar teams en modern werk",
    back: "Terug naar al het materiaal",
    funding: "Ondersteund door de Nederlandse Organisatie voor Wetenschappelijk Onderzoek (NWO)",
    heroEye: "Voor praktijk en onderwijs",
    heroTitle: "Materiaal over werken in meerdere teams",
    heroLead: "Veel mensen verdelen hun werkweek over meerdere teams. Het aantal teams vertelt maar een deel van het verhaal. Met dit gratis materiaal bekijkt u hoe het werk werkelijk is ingericht.",
    practitionerButton: "Voor de praktijk",
    educatorButton: "Voor docenten",
    sameCount: "Hetzelfde aantal teams",
    weekA: "Week A",
    weekB: "Week B",
    anchored: "Eén duidelijk basisteam",
    fragmented: "Tijd verdeeld in kleine stukken",
    differentWeeks: "Verschillende werkweken",
    definitionEye: "Een korte uitleg",
    definitionTitle: "Wat is multiple team membership?",
    definitionOne: "Multiple team membership betekent dat één persoon in dezelfde periode in twee of meer teams werkt. Dat gebeurt in projectwerk, zorg, onderwijs, publieke dienstverlening, fabrieken, logistiek, advieswerk, en veel andere werkomgevingen.",
    definitionTwo: "Deze manier van werken kan nuttige ervaring door een organisatie verspreiden. Zij kan ook leiden tot vaak wisselen, botsende prioriteiten, en onduidelijke verwachtingen. Een goede analyse begint bij de inrichting van het werk, niet bij één algemene grens voor het aantal teams.",
    practiceEye: "Voor de praktijk",
    practiceTitle: "Breng uw eigen teamportfolio in kaart",
    practiceIntro: "Gebruik de vragen om een vaak onzichtbare werkindeling bespreekbaar te maken. De tool geeft suggesties voor de medewerker en de leidinggevende, plus een klein experiment voor twee weken.",
    toolLabel: "Interactieve reflectietool",
    toolTitle: "Meer Dan Een Getal: MTM Portfolio Navigator",
    toolBody: "Beantwoord vragen over wisselen, tijd, rollen, vertrouwdheid, veranderende teams, en status. De tool legt uit welke antwoorden tot elke suggestie leidden en koppelt het advies aan het onderliggende onderzoek.",
    toolPointOne: "Kost ongeveer vijf minuten.",
    toolPointTwo: "Geen account nodig.",
    toolPointThree: "Antwoorden blijven in uw browser.",
    toolPointFour: "Geen persoonlijkheidslabel of algemene risicoscore.",
    openTool: "Open de MTM Navigator",
    useToolEye: "Gebruik de uitkomst in een echt gesprek",
    useToolTitle: "Neem de uitkomst mee naar een een-op-een- of teamontwerpgesprek",
    useToolBody: "Kies één patroon dat aandacht nodig heeft. Spreek één verandering af, wie daarbij moet helpen, en wat u na twee weken controleert. De uitkomst is het begin van een gesprek, geen test van de medewerker.",
    educatorEye: "Voor docenten",
    educatorTitle: "Twee cases die klaar zijn voor gebruik",
    educatorIntro: "Elke case heeft een studentenversie en een aparte uitwerking. De taal is eenvoudig genoeg voor studenten die nog niet eerder over werken in meerdere teams hebben geleerd.",
    statusLabel: "Status en terugkeer naar een team",
    statusTitle: "Terug van de taskforce",
    statusBody: "Maya keert terug naar haar vaste team na een zichtbare opdracht elders. Haar formele rol is niet veranderd, maar haar positie in de twee teams verschilt. De klas beslist hoe haar leidinggevende haar ervaring kan benutten zonder van de terugkeer een statusstrijd te maken.",
    caseTimeLabel: "Lestijd",
    statusTime: "30 tot 40 minuten",
    caseUseLabel: "Geschikt voor",
    statusUse: "Teamwork, leiderschap, en status",
    downloadCase: "Download de case",
    downloadGuide: "Download de uitwerking",
    fourLabel: "Werkontwerp en wisselen",
    fourTitle: "Vier teams, twee heel verschillende weken",
    fourBody: "Ruben en Aisha werken allebei in vier teams bij een distributiecentrum. De een heeft een duidelijk basisteam en beschermde werkblokken. De ander wisselt de hele dag tussen teams. De klas moet het werk opnieuw inrichten zonder te doen alsof één teamgrens voor iedereen werkt.",
    caseTimeLabelTwo: "Lestijd",
    fourTime: "30 tot 40 minuten",
    caseUseLabelTwo: "Geschikt voor",
    fourUse: "Teamwork, HR, en werkontwerp",
    downloadCaseTwo: "Download de case",
    downloadGuideTwo: "Download de uitwerking",
    thirdEye: "Een derde case in de cursus",
    thirdBody: "Deze twee openbare cases vullen een langere multiple team membership-case aan die Joost van de Brake gebruikt in zijn cursus Teamwork. Samen behandelen zij teaminrichting, wisselen, status, en praktisch werkontwerp.",
    evidenceEye: "Onderzoeksbasis",
    evidenceTitle: "Het materiaal laat zien waar de ideeën vandaan komen",
    evidenceIntro: "De eerste case gebruikt een lopend manuscript en vermeldt duidelijk dat het nog onder review is. De tweede case gebruikt een gepubliceerde studie. Beide cases zijn fictieve onderwijsbewerkingen, geen nieuwe onderzoeken.",
    statusEvidenceLabel: "Onder review",
    statusEvidenceTitle: "Returning with a Different Status Position",
    statusEvidenceBody: "De studie onderzoekt terugkeermomenten in het betaald voetbal en vraagt wat er gebeurt wanneer iemands relatieve status verschilt tussen een voormalig en een huidig team.",
    statusCitation: "Van de Brake. Manuscript onder review bij Organization Science.",
    openEvidence: "Open het onderzoeksmateriaal",
    fourEvidenceLabel: "Gepubliceerd",
    fourEvidenceTitle: "More Than Just a Number",
    fourEvidenceBody: "De studie laat zien waarom wisselen, tijdsverdeling, een duidelijk basisteam, en eerdere vertrouwdheid meer kunnen vertellen dan alleen het aantal teams.",
    fourCitation: "Van de Brake, Van der Vegt, en Essens (2024), Journal of Applied Psychology.",
    openPaper: "Open het artikel",
    contactEye: "Vragen of ervaringen uit de les",
    contactTitle: "Vertel me hoe u het materiaal gebruikte",
    contactBody: "Gebruikt u een case in de les of probeert u de tool in een organisatie? Dan hoor ik graag wat goed werkte en wat onduidelijk was.",
    footerTitle: "Materiaal over werken in meerdere teams",
    footerFunding: "Ondersteund door de Nederlandse Organisatie voor Wetenschappelijk Onderzoek (NWO). Het onderwijsmateriaal en de praktische tool zijn onderzoeksgebaseerde bewerkingen van Joost van de Brake.",
    contactLink: "Contact",
    researchLink: "Onderzoek",
    allResourcesLink: "Al het materiaal"
  }
};
