window.MTM_RESOURCE_COPY = {
  en: {},
  nl: {
    skip: "Ga naar het materiaal",
    brandSub: "Onderzoek naar teams en modern werk",
    back: "Terug naar al het materiaal",
    funding: "Ondersteund door NWO",
    heroEye: "Werken in meerdere teams",
    heroTitle: "Wanneer meerdere teams om dezelfde werkweek vragen",
    heroLead: "Veel mensen werken in dezelfde periode voor meerdere teams. Elk team brengt eigen vergaderingen, deadlines, werkrelaties en verwachtingen mee. Ervaring uit het ene team kan helpen in het andere, terwijl dezelfde inrichting ook de aandacht kan verdelen en prioriteiten onduidelijk kan maken.",
    heroLeadTwo: "De belasting hangt af van de manier waarop de teamlidmaatschappen samenhangen. Iemand met een duidelijk basisteam en beschermde tijdsblokken heeft een andere werkweek dan iemand die de hele dag tussen teams wisselt, ook wanneer beiden in evenveel teams werken. De MTM Portfolio Navigator helpt mensen die inrichting in kaart te brengen, te zien waar druk ontstaat, te behouden wat goed werkt en een kleine verandering in het werk te kiezen om uit te proberen.",
    practitionerButton: "Start de Navigator van 5 minuten",
    exampleButton: "Bekijk een voorbeelduitkomst",
    heroNote: "Gebouwd op het onderzoek van Joost van de Brake naar werken in meerdere teams.",
    previewAria: "Voorbeelduitkomst van de MTM Portfolio Navigator",
    previewLabel: "Voorbeelduitkomst",
    previewTeams: "4 teams",
    previewPriorityLabel: "Eerste aandachtspunt",
    previewPriorityTitle: "Bescherm langere focusblokken",
    previewPriorityBody: "Vaak wisselen verdeelt de week in kleine stukken.",
    previewStrengthLabel: "Wat helpt",
    previewStrength: "Ervaring reist mee tussen teams",
    previewTestLabel: "Proef van twee weken",
    previewTest: "Bescherm twee blokken van 75 minuten en houd ongeplande wisselingen bij",
    practiceEye: "Een praktische tool voor modern teamwerk",
    practiceTitle: "Maak een ingewikkelde werkweek makkelijker te begrijpen",
    practiceIntro: "Uw teamportfolio is het geheel van teams waarin u in dezelfde periode werkt. De Navigator maakt de vorm van dat portfolio zichtbaar.",
    toolLabel: "Gratis interactieve Navigator",
    toolTitle: "Meer dan een getal: MTM Portfolio Navigator",
    toolBody: "Beschrijf hoe uw tijd is verdeeld en hoe vaak u tussen teams wisselt. De Navigator zet uw antwoorden om in een helder overzicht. Elke suggestie legt uit waarom zij verscheen en opent het onderzoek erachter.",
    openTool: "Start de Navigator van 5 minuten",
    useToolEye: "Voor wie is de Navigator?",
    useToolTitle: "Breng een echte werkweek in het gesprek",
    audienceOneTitle: "Medewerkers",
    audienceOneBody: "die een gesprek over werkdruk voorbereiden.",
    audienceTwoTitle: "Leidinggevenden",
    audienceTwoBody: "die bekijken hoe het werk is verdeeld.",
    audienceThreeTitle: "HR-professionals",
    audienceThreeBody: "die bezetting en teamontwerp bespreken.",
    audienceFourTitle: "Docenten",
    audienceFourBody: "die multiple team membership uitleggen.",
    processEye: "Zo werkt het",
    processTitle: "Van uw werkweek naar een praktische volgende stap",
    processOneTitle: "Beschrijf uw week",
    processOneBody: "Beantwoord korte vragen over uw teams en hoe het werk ertussen beweegt.",
    processTwoTitle: "Bekijk uw overzicht",
    processTwoBody: "Zie uw teamportfolio en de vijf werkpatronen die het vormen.",
    processThreeTitle: "Kies een suggestie",
    processThreeBody: "Gebruik de uitleg om te bepalen welk patroon als eerste aandacht nodig heeft.",
    processFourTitle: "Probeer één verandering",
    processFourBody: "Bepaal wie meedoet en wat u wilt volgen. Stel een evaluatiedatum vast en bewaar of print het plan.",
    definitionEye: "De basis",
    definitionTitle: "Kijk hoe de teams samenhangen",
    definitionOne: "Multiple team membership betekent dat iemand in dezelfde periode in twee of meer teams werkt. Dit komt voor in de zorg, publieke dienstverlening, logistiek, productie, onderwijs, projectwerk, en veel andere omgevingen.",
    definitionTwo: "De dagelijkse ervaring hangt af van de inrichting van die lidmaatschappen. De ene persoon heeft een duidelijk basisteam en lange blokken met geconcentreerd werk. De andere wisselt de hele dag tussen teams. De Navigator helpt beide mensen hun situatie te beschrijven en een werkbare verandering te kiezen.",
    figureAlt: "Iemand met een laptop onder de arm loopt van een overleg met drie collega’s naar een overleg met drie anderen, over een pad dat de twee teams verbindt.",
    educatorEye: "Voor docenten",
    educatorTitle: "Twee direct inzetbare cases over werken in meerdere teams",
    educatorIntro: "Elke case bevat een studentenversie en een aparte docentenhandleiding. De verhalen spelen in herkenbare werksituaties en leggen het onderzoek in eenvoudige taal uit.",
    educatorToolEye: "Begin de les met de Navigator",
    educatorToolTitle: "Laat studenten een echte werkweek in kaart brengen",
    educatorToolBody: "Studenten kunnen de Navigator invullen vanuit een baan, stage, vrijwilligersrol, of fictieve medewerker. Daarna beginnen zij aan de cases met een concreet voorbeeld van hoe teamindelingen verschillen.",
    educatorToolButton: "Start de Navigator in de les",
    statusLabel: "Status en terugkeer naar een team",
    statusTitle: "Terug in het vaste team",
    statusBody: "Maya keert na zes weken in een tijdelijk verbeterteam terug naar haar vaste team. In dat team luisterden mensen vaker naar haar dan in Atlas. Studenten beslissen hoe haar leidinggevende Maya’s nieuwe idee en Rubens lokale kennis kan gebruiken om een echt overdrachtsprobleem op te lossen.",
    caseTimeLabel: "Lestijd",
    statusTime: "30 tot 40 minuten",
    caseUseLabel: "Onderwerpen",
    statusUse: "Teamwork, leiderschap, status, en terugkeer naar een team",
    downloadCase: "Download de studentencase",
    downloadGuide: "Download de docentenhandleiding",
    fourLabel: "Werkontwerp en wisselen",
    fourTitle: "Vier teams, twee heel verschillende weken",
    fourBody: "Ruben en Aisha werken allebei in vier teams bij een distributiecentrum. Ruben heeft een duidelijk basisteam en beschermde werkblokken. Aisha wisselt de hele dag tussen teams. Studenten vergelijken hun werkweken en ontwerpen de meer versnipperde werksituatie opnieuw.",
    caseTimeLabelTwo: "Lestijd",
    fourTime: "30 tot 40 minuten",
    caseUseLabelTwo: "Onderwerpen",
    fourUse: "Teamwork, HR, roosters, en werkontwerp",
    downloadCaseTwo: "Download de studentencase",
    downloadGuideTwo: "Download de docentenhandleiding",
    thirdEye: "Een derde case in de cursus Teamwork",
    thirdBody: "Deze openbare cases vullen een langere case aan uit de cursus Teamwork van Joost van de Brake. Met de drie cases leren studenten eerst een teamportfolio in kaart te brengen en daarna keuzes te maken over leiderschap en werkontwerp.",
    evidenceEye: "Onderzoek achter de Navigator",
    evidenceTitle: "Bekijk het onderzoek achter elke suggestie",
    evidenceIntro: "De Navigator zet een onderzoeksprogramma over werken in meerdere teams om in vragen over de eigen werksituatie. Deze vier gepubliceerde artikelen vormen de belangrijkste basis. De tool toont ook actuele studies wanneer die een suggestie onderbouwen.",
    researchOneLabel: "Tijd en wisselen",
    researchOneTitle: "More Than Just a Number",
    researchOneBody: "De studie onderscheidt het aantal teams van tijdsverdeling, wisselen, een duidelijk basisteam, en vertrouwdheid met teamleden.",
    researchOneLink: "Journal of Applied Psychology, 2024",
    researchTwoLabel: "Rollen tussen teams",
    researchTwoTitle: "Can I Leave My Hat On?",
    researchTwoBody: "De studie onderzoekt hoe verschillen in iemands rollen tussen teams samenhangen met rolonduidelijkheid en teamprestaties.",
    researchTwoLink: "Personnel Psychology, 2023",
    researchThreeLabel: "Ervaring in de organisatie",
    researchThreeTitle: "Benefits and Disadvantages of Multiple Team Membership",
    researchThreeBody: "De verbanden verschilden tussen nieuwere en langer zittende medewerkers, zowel in hun werkervaring als in hun latere prestaties.",
    researchThreeLink: "Journal of Management Studies, 2020",
    researchFourLabel: "Voordelen en belasting",
    researchFourTitle: "Resource Leverage, Resource Depletion",
    researchFourBody: "Werken in meerdere teams kan toegang geven tot hulpbronnen in de organisatie en tegelijk extra belasting veroorzaken.",
    researchFourLink: "Journal of Applied Psychology, 2022",
    caseEvidenceTitle: "Onderzoek achter de onderwijscases",
    caseEvidenceIntro: "Elke case legt uit welk bewijs erachter zit en hoe ver dat bewijs kan worden gebruikt. Het fictieve verhaal zet de onderzoeksvraag om in een beslissing die studenten kunnen bespreken.",
    statusEvidenceLabel: "Lopend onderzoek",
    statusEvidenceTitle: "Statusverschillen wanneer mensen terugkeren naar een team",
    statusEvidenceBody: "De studie volgt 692 momenten waarop voetballers na deelname aan hun nationale team terugkeerden naar hun club. Grotere verschillen in relatieve status tussen beide teams hingen samen met meer gecreëerde kansen voor clubgenoten.",
    statusCitation: "Lopend onderzoek van Joost van de Brake naar statusverschillen tussen teamlidmaatschappen.",
    openEvidence: "Bekijk het onderzoek van Joost",
    fourEvidenceLabel: "Gepubliceerd",
    fourEvidenceTitle: "Waarom twee mensen in vier teams verschillende weken hebben",
    fourEvidenceBody: "De studie vergelijkt verschillende manieren om werken in meerdere teams te beschrijven. Zij laat zien hoe tijdsverdeling, wisselen, een duidelijk basisteam, en eerdere vertrouwdheid een teamindeling vormen.",
    fourCitation: "Van de Brake, Van der Vegt, en Essens (2024), Journal of Applied Psychology.",
    openPaper: "Lees het gepubliceerde artikel",
    contactEye: "Deel uw ervaring",
    contactTitle: "Vertel me hoe de Navigator of cases voor u werkten",
    contactBody: "Gebruikt u de Navigator of een van de cases? Stuur me dan een kort bericht. Ervaringen uit organisaties en lessen helpen mij om volgend materiaal verder te verbeteren.",
    footerTitle: "MTM Portfolio Navigator en onderwijsmateriaal",
    footerFunding: "Ondersteund door NWO. Ontwikkeld door Joost van de Brake op basis van zijn onderzoek naar multiple team membership.",
    contactLink: "Contact",
    researchLink: "Onderzoek",
    allResourcesLink: "Al het materiaal"
  }
};
